export const states = [
  {
    id: 1,
    name: "Abia",
    lga: [
      { id: 1, name: "Aba South" },
      { id: 2, name: "Arochukwu" },
      { id: 3, name: "Bende" },
      { id: 4, name: "Ikwuano" },
      { id: 5, name: "Isiala Ngwa North" },
      { id: 6, name: "Isiala Ngwa South" },
      { id: 7, name: "Isuikwuato" },
      { id: 8, name: "Obi Ngwa" },
      { id: 9, name: "Ohafia" },
      { id: 10, name: "Osisioma" },
      { id: 11, name: "Ugwunagbo" },
      { id: 12, name: "Ukwa East" },
      { id: 13, name: "Ukwa West" },
      { id: 14, name: "Umuahia North" },
      { id: 15, name: "Umuahia South" },
      { id: 16, name: "Umu Nneochi" },
    ],
    code: "000088",
  },
  {
    id: 2,
    name: "Adamawa",
    lga: [
      { id: 17, name: "Fufure" },
      { id: 18, name: "Ganye" },
      { id: 19, name: "Gayuk" },
      { id: 20, name: "Gombi" },
      { id: 21, name: "Grie" },
      { id: 22, name: "Hong" },
      { id: 23, name: "Jada" },
      { id: 24, name: "Lamurde" },
      { id: 25, name: "Madagali" },
      { id: 26, name: "Maiha" },
      { id: 27, name: "Mayo Belwa" },
      { id: 28, name: "Michika" },
      { id: 29, name: "Mubi North" },
      { id: 30, name: "Mubi South" },
      { id: 31, name: "Numan" },
      { id: 32, name: "Shelleng" },
      { id: 33, name: "Song" },
      { id: 34, name: "Toungo" },
      { id: 35, name: "Yola North" },
      { id: 36, name: "Yola South" },
    ],
    code: "000075",
  },
  {
    id: 3,
    name: "Akwa Ibom",
    lga: [
      { id: 37, name: "Eastern Obolo" },
      { id: 38, name: "Eket" },
      { id: 39, name: "Esit Eket" },
      { id: 40, name: "Essien Udim" },
      { id: 41, name: "Etim Ekpo" },
      { id: 42, name: "Etinan" },
      { id: 43, name: "Ibeno" },
      { id: 44, name: "Ibesikpo Asutan" },
      { id: 45, name: "Ibiono-Ibom" },
      { id: 46, name: "Ika" },
      { id: 47, name: "Ikono" },
      { id: 48, name: "Ikot Abasi" },
      { id: 49, name: "Ikot Ekpene" },
      { id: 50, name: "Ini" },
      { id: 51, name: "Itu" },
      { id: 52, name: "Mbo" },
      { id: 53, name: "Mkpat-Enin" },
      { id: 54, name: "Nsit-Atai" },
      { id: 55, name: "Nsit-Ibom" },
      { id: 56, name: "Nsit-Ubium" },
      { id: 57, name: "Obot Akara" },
      { id: 58, name: "Okobo" },
      { id: 59, name: "Onna" },
      { id: 60, name: "Oron" },
      { id: 61, name: "Oruk Anam" },
      { id: 62, name: "Udung-Uko" },
      { id: 63, name: "Ukanafun" },
      { id: 64, name: "Uruan" },
      { id: 65, name: "Urue-Offong/Oruko" },
      { id: 66, name: "Uyo" },
    ],
    code: "000085",
  },
  {
    id: 4,
    name: "Anambra",
    lga: [
      { id: 67, name: "Anambra East" },
      { id: 68, name: "Anambra West" },
      { id: 69, name: "Anaocha" },
      { id: 70, name: "Awka North" },
      { id: 71, name: "Awka South" },
      { id: 72, name: "Ayamelum" },
      { id: 73, name: "Dunukofia" },
      { id: 74, name: "Ekwusigo" },
      { id: 75, name: "Idemili North" },
      { id: 76, name: "Idemili South" },
      { id: 77, name: "Ihiala" },
      { id: 78, name: "Njikoka" },
      { id: 79, name: "Nnewi North" },
      { id: 80, name: "Nnewi South" },
      { id: 81, name: "Ogbaru" },
      { id: 82, name: "Onitsha North" },
      { id: 83, name: "Onitsha South" },
      { id: 84, name: "Orumba North" },
      { id: 85, name: "Orumba South" },
      { id: 86, name: "Oyi" },
    ],
    code: "000048",
  },
  {
    id: 5,
    name: "Bauchi",
    lga: [
      { id: 87, name: "Bauchi" },
      { id: 88, name: "Bogoro" },
      { id: 89, name: "Damban" },
      { id: 90, name: "Darazo" },
      { id: 91, name: "Dass" },
      { id: 92, name: "Gamawa" },
      { id: 93, name: "Ganjuwa" },
      { id: 94, name: "Giade" },
      { id: 95, name: "Itas/Gadau" },
      { id: 96, name: "Jama'are" },
      { id: 97, name: "Katagum" },
      { id: 98, name: "Kirfi" },
      { id: 99, name: "Misau" },
      { id: 100, name: "Ningi" },
      { id: 101, name: "Shira" },
      { id: 102, name: "Tafawa Balewa" },
      { id: 103, name: "Toro" },
      { id: 104, name: "Warji" },
      { id: 105, name: "Zaki" },
    ],
    code: "000077",
  },
  {
    id: 6,
    name: "Bayelsa",
    lga: [
      { id: 106, name: "Ekeremor" },
      { id: 107, name: "Kolokuma/Opokuma" },
      { id: 108, name: "Nembe" },
      { id: 109, name: "Ogbia" },
      { id: 110, name: "Sagbama" },
      { id: 111, name: "Southern Ijaw" },
      { id: 112, name: "Yenagoa" },
    ],
    code: "000089",
  },
  {
    id: 7,
    name: "Benue",
    lga: [
      { id: 113, name: "Apa" },
      { id: 114, name: "Ado" },
      { id: 115, name: "Buruku" },
      { id: 116, name: "Gboko" },
      { id: 117, name: "Guma" },
      { id: 118, name: "Gwer East" },
      { id: 119, name: "Gwer West" },
      { id: 120, name: "Katsina-Ala" },
      { id: 121, name: "Konshisha" },
      { id: 122, name: "Kwande" },
      { id: 123, name: "Logo" },
      { id: 124, name: "Makurdi" },
      { id: 125, name: "Obi" },
      { id: 126, name: "Ogbadibo" },
      { id: 127, name: "Ohimini" },
      { id: 128, name: "Oju" },
      { id: 129, name: "Okpokwu" },
      { id: 130, name: "Oturkpo" },
      { id: 131, name: "Tarka" },
      { id: 132, name: "Ukum" },
      { id: 133, name: "Ushongo" },
      { id: 134, name: "Vandeikya" },
    ],
    code: "000044",
  },
  {
    id: 8,
    name: "Borno",
    lga: [
      { id: 135, name: "Askira/Uba" },
      { id: 136, name: "Bama" },
      { id: 137, name: "Bayo" },
      { id: 138, name: "Biu" },
      { id: 139, name: "Chibok" },
      { id: 140, name: "Damboa" },
      { id: 141, name: "Dikwa" },
      { id: 142, name: "Gubio" },
      { id: 143, name: "Guzamala" },
      { id: 144, name: "Gwoza" },
      { id: 145, name: "Hawul" },
      { id: 146, name: "Jere" },
      { id: 147, name: "Kaga" },
      { id: 148, name: "Kala/Balge" },
      { id: 149, name: "Konduga" },
      { id: 150, name: "Kukawa" },
      { id: 151, name: "Kwaya Kusar" },
      { id: 152, name: "Mafa" },
      { id: 153, name: "Magumeri" },
      { id: 154, name: "Maiduguri" },
      { id: 155, name: "Marte" },
      { id: 156, name: "Mobbar" },
      { id: 157, name: "Monguno" },
      { id: 158, name: "Ngala" },
      { id: 159, name: "Nganzai" },
      { id: 160, name: "Shani" },
    ],
    code: "000076",
  },
  {
    id: 9,
    name: "Cross River",
    lga: [
      { id: 161, name: "Akamkpa" },
      { id: 162, name: "Akpabuyo" },
      { id: 163, name: "Bakassi" },
      { id: 164, name: "Bekwarra" },
      { id: 165, name: "Biase" },
      { id: 166, name: "Boki" },
      { id: 167, name: "Calabar Municipal" },
      { id: 168, name: "Calabar South" },
      { id: 169, name: "Etung" },
      { id: 170, name: "Ikom" },
      { id: 171, name: "Obanliku" },
      { id: 172, name: "Obubra" },
      { id: 173, name: "Obudu" },
      { id: 174, name: "Odukpani" },
      { id: 175, name: "Ogoja" },
      { id: 176, name: "Yakuur" },
      { id: 177, name: "Yala" },
    ],
    code: "000087",
  },
  {
    id: 10,
    name: "Delta",
    lga: [
      { id: 178, name: "Aniocha South" },
      { id: 179, name: "Bomadi" },
      { id: 180, name: "Burutu" },
      { id: 181, name: "Ethiope East" },
      { id: 182, name: "Ethiope West" },
      { id: 183, name: "Ika North East" },
      { id: 184, name: "Ika South" },
      { id: 185, name: "Isoko North" },
      { id: 186, name: "Isoko South" },
      { id: 187, name: "Ndokwa East" },
      { id: 188, name: "Ndokwa West" },
      { id: 189, name: "Okpe" },
      { id: 190, name: "Oshimili North" },
      { id: 191, name: "Oshimili South" },
      { id: 192, name: "Patani" },
      { id: 193, name: "Sapele" },
      { id: 194, name: "Udu" },
      { id: 195, name: "Ughelli North" },
      { id: 196, name: "Ughelli South" },
      { id: 197, name: "Ukwuani" },
      { id: 198, name: "Uvwie" },
      { id: 199, name: "Warri North" },
      { id: 200, name: "Warri South" },
      { id: 201, name: "Warri South West" },
    ],
    code: "000056",
  },
  {
    id: 11,
    name: "Ebonyi",
    lga: [
      { id: 202, name: "Afikpo North" },
      { id: 203, name: "Afikpo South" },
      { id: 204, name: "Ebonyi" },
      { id: 205, name: "Ezza North" },
      { id: 206, name: "Ezza South" },
      { id: 207, name: "Ikwo" },
      { id: 208, name: "Ishielu" },
      { id: 209, name: "Ivo" },
      { id: 210, name: "Izzi" },
      { id: 211, name: "Ohaozara" },
      { id: 212, name: "Ohaukwu" },
      { id: 213, name: "Onicha" },
    ],
    code: "000043",
  },
  {
    id: 12,
    name: "Edo",
    lga: [
      { id: 214, name: "Egor" },
      { id: 215, name: "Esan Central" },
      { id: 216, name: "Esan North-East" },
      { id: 217, name: "Esan South-East" },
      { id: 218, name: "Esan West" },
      { id: 219, name: "Etsako Central" },
      { id: 220, name: "Etsako East" },
      { id: 221, name: "Etsako West" },
      { id: 222, name: "Igueben" },
      { id: 223, name: "Ikpoba Okha" },
      { id: 224, name: "Orhionmwon" },
      { id: 225, name: "Oredo" },
      { id: 226, name: "Ovia North-East" },
      { id: 227, name: "Ovia South-West" },
      { id: 228, name: "Owan East" },
      { id: 229, name: "Owan West" },
      { id: 230, name: "Uhunmwonde" },
    ],
    code: "000052",
  },
  {
    id: 13,
    name: "Ekiti",
    lga: [
      { id: 231, name: "Efon" },
      { id: 232, name: "Ekiti East" },
      { id: 233, name: "Ekiti South-West" },
      { id: 234, name: "Ekiti West" },
      { id: 235, name: "Emure" },
      { id: 236, name: "Gbonyin" },
      { id: 237, name: "Ido Osi" },
      { id: 238, name: "Ijero" },
      { id: 239, name: "Ikere" },
      { id: 240, name: "Ikole" },
      { id: 241, name: "Ilejemeje" },
      { id: 242, name: "Irepodun/Ifelodun" },
      { id: 243, name: "Ise/Orun" },
      { id: 244, name: "Moba" },
      { id: 245, name: "Oye" },
    ],
    code: "000030",
  },
  {
    id: 14,
    name: "Enugu",
    lga: [
      { id: 246, name: "Awgu" },
      { id: 247, name: "Enugu East" },
      { id: 248, name: "Enugu North" },
      { id: 249, name: "Enugu South" },
      { id: 250, name: "Ezeagu" },
      { id: 251, name: "Igbo Etiti" },
      { id: 252, name: "Igbo Eze North" },
      { id: 253, name: "Igbo Eze South" },
      { id: 254, name: "Isi Uzo" },
      { id: 255, name: "Nkanu East" },
      { id: 256, name: "Nkanu West" },
      { id: 257, name: "Nsukka" },
      { id: 258, name: "Oji River" },
      { id: 259, name: "Udenu" },
      { id: 260, name: "Udi" },
      { id: 261, name: "Uzo Uwani" },
    ],
    code: "000042",
  },
  {
    id: 15,
    name: "FCT",
    lga: [
      { id: 262, name: "Bwari" },
      { id: 263, name: "Gwagwalada" },
      { id: 264, name: "Kuje" },
      { id: 265, name: "Kwali" },
      { id: 266, name: "Municipal Area Council" },
    ],
    code: "000090",
  },
  {
    id: 16,
    name: "Gombe",
    lga: [
      { id: 267, name: "Balanga" },
      { id: 268, name: "Billiri" },
      { id: 269, name: "Dukku" },
      { id: 270, name: "Funakaye" },
      { id: 271, name: "Gombe" },
      { id: 272, name: "Kaltungo" },
      { id: 273, name: "Kwami" },
      { id: 274, name: "Nafada" },
      { id: 275, name: "Shongom" },
      { id: 276, name: "Yamaltu/Deba" },
    ],
    code: "000072",
  },
  {
    id: 17,
    name: "Imo",
    lga: [
      { id: 277, name: "Ahiazu Mbaise" },
      { id: 278, name: "Ehime Mbano" },
      { id: 279, name: "Ezinihitte" },
      { id: 280, name: "Ideato North" },
      { id: 281, name: "Ideato South" },
      { id: 282, name: "Ihitte/Uboma" },
      { id: 283, name: "Ikeduru" },
      { id: 284, name: "Isiala Mbano" },
      { id: 285, name: "Isu" },
      { id: 286, name: "Mbaitoli" },
      { id: 287, name: "Ngor Okpala" },
      { id: 288, name: "Njaba" },
      { id: 289, name: "Nkwerre" },
      { id: 290, name: "Nwangele" },
      { id: 291, name: "Obowo" },
      { id: 292, name: "Oguta" },
      { id: 293, name: "Ohaji/Egbema" },
      { id: 294, name: "Okigwe" },
      { id: 295, name: "Orlu" },
      { id: 296, name: "Orsu" },
      { id: 297, name: "Oru East" },
      { id: 298, name: "Oru West" },
      { id: 299, name: "Owerri Municipal" },
      { id: 300, name: "Owerri North" },
      { id: 301, name: "Owerri West" },
      { id: 302, name: "Unuimo" },
    ],
    code: "000083",
  },
  {
    id: 18,
    name: "Jigawa",
    lga: [
      { id: 303, name: "Babura" },
      { id: 304, name: "Biriniwa" },
      { id: 305, name: "Birnin Kudu" },
      { id: 306, name: "Buji" },
      { id: 307, name: "Dutse" },
      { id: 308, name: "Gagarawa" },
      { id: 309, name: "Garki" },
      { id: 310, name: "Gumel" },
      { id: 311, name: "Guri" },
      { id: 312, name: "Gwaram" },
      { id: 313, name: "Gwiwa" },
      { id: 314, name: "Hadejia" },
      { id: 315, name: "Jahun" },
      { id: 316, name: "Kafin Hausa" },
      { id: 317, name: "Kazaure" },
      { id: 318, name: "Kiri Kasama" },
      { id: 319, name: "Kiyawa" },
      { id: 320, name: "Kaugama" },
      { id: 321, name: "Maigatari" },
      { id: 322, name: "Malam Madori" },
      { id: 323, name: "Miga" },
      { id: 324, name: "Ringim" },
      { id: 325, name: "Roni" },
      { id: 326, name: "Sule Tankarkar" },
      { id: 327, name: "Taura" },
      { id: 328, name: "Yankwashi" },
    ],
    code: "000078",
  },
  {
    id: 19,
    name: "Kaduna",
    lga: [
      { id: 329, name: "Chikun" },
      { id: 330, name: "Giwa" },
      { id: 331, name: "Igabi" },
      { id: 332, name: "Ikara" },
      { id: 333, name: "Jaba" },
      { id: 334, name: "Jema'a" },
      { id: 335, name: "Kachia" },
      { id: 336, name: "Kaduna North" },
      { id: 337, name: "Kaduna South" },
      { id: 338, name: "Kagarko" },
      { id: 339, name: "Kajuru" },
      { id: 340, name: "Kaura" },
      { id: 341, name: "Kauru" },
      { id: 342, name: "Kubau" },
      { id: 343, name: "Kudan" },
      { id: 344, name: "Lere" },
      { id: 345, name: "Makarfi" },
      { id: 346, name: "Sabon Gari" },
      { id: 347, name: "Sanga" },
      { id: 348, name: "Soba" },
      { id: 349, name: "Zangon Kataf" },
      { id: 350, name: "Zaria" },
    ],
    code: "000062",
  },
  {
    id: 20,
    name: "Kano",
    lga: [
      { id: 351, name: "Albasu" },
      { id: 352, name: "Bagwai" },
      { id: 353, name: "Bebeji" },
      { id: 354, name: "Bichi" },
      { id: 355, name: "Bunkure" },
      { id: 356, name: "Dala" },
      { id: 357, name: "Dambatta" },
      { id: 358, name: "Dawakin Kudu" },
      { id: 359, name: "Dawakin Tofa" },
      { id: 360, name: "Doguwa" },
      { id: 361, name: "Fagge" },
      { id: 362, name: "Gabasawa" },
      { id: 363, name: "Garko" },
      { id: 364, name: "Garun Mallam" },
      { id: 365, name: "Gaya" },
      { id: 366, name: "Gezawa" },
      { id: 367, name: "Gwale" },
      { id: 368, name: "Gwarzo" },
      { id: 369, name: "Kabo" },
      { id: 370, name: "Kano Municipal" },
      { id: 371, name: "Karaye" },
      { id: 372, name: "Kibiya" },
      { id: 373, name: "Kiru" },
      { id: 374, name: "Kumbotso" },
      { id: 375, name: "Kunchi" },
      { id: 376, name: "Kura" },
      { id: 377, name: "Madobi" },
      { id: 378, name: "Makoda" },
      { id: 379, name: "Minjibir" },
      { id: 380, name: "Nasarawa" },
      { id: 381, name: "Rano" },
      { id: 382, name: "Rimin Gado" },
      { id: 383, name: "Rogo" },
      { id: 384, name: "Shanono" },
      { id: 385, name: "Sumaila" },
      { id: 386, name: "Takai" },
      { id: 387, name: "Tarauni" },
      { id: 388, name: "Tofa" },
      { id: 389, name: "Tsanyawa" },
      { id: 390, name: "Tudun Wada" },
      { id: 391, name: "Ungogo" },
      { id: 392, name: "Warawa" },
      { id: 393, name: "Wudil" },
    ],
    code: "000064",
  },
  {
    id: 21,
    name: "Katsina",
    lga: [
      { id: 394, name: "Batagarawa" },
      { id: 395, name: "Batsari" },
      { id: 396, name: "Baure" },
      { id: 397, name: "Bindawa" },
      { id: 398, name: "Charanchi" },
      { id: 399, name: "Dandume" },
      { id: 400, name: "Danja" },
      { id: 401, name: "Dan Musa" },
      { id: 402, name: "Daura" },
      { id: 403, name: "Dutsi" },
      { id: 404, name: "Dutsin Ma" },
      { id: 405, name: "Faskari" },
      { id: 406, name: "Funtua" },
      { id: 407, name: "Ingawa" },
      { id: 408, name: "Jibia" },
      { id: 409, name: "Kafur" },
      { id: 410, name: "Kaita" },
      { id: 411, name: "Kankara" },
      { id: 412, name: "Kankia" },
      { id: 413, name: "Katsina" },
      { id: 414, name: "Kurfi" },
      { id: 415, name: "Kusada" },
      { id: 416, name: "Mai'Adua" },
      { id: 417, name: "Malumfashi" },
      { id: 418, name: "Mani" },
      { id: 419, name: "Mashi" },
      { id: 420, name: "Matazu" },
      { id: 421, name: "Musawa" },
      { id: 422, name: "Rimi" },
      { id: 423, name: "Sabuwa" },
      { id: 424, name: "Safana" },
      { id: 425, name: "Sandamu" },
      { id: 426, name: "Zango" },
    ],
    code: "000065",
  },
  {
    id: 22,
    name: "Kebbi",
    lga: [
      { id: 427, name: "Arewa Dandi" },
      { id: 428, name: "Argungu" },
      { id: 429, name: "Augie" },
      { id: 430, name: "Bagudo" },
      { id: 431, name: "Birnin Kebbi" },
      { id: 432, name: "Bunza" },
      { id: 433, name: "Dandi" },
      { id: 434, name: "Fakai" },
      { id: 435, name: "Gwandu" },
      { id: 436, name: "Jega" },
      { id: 437, name: "Kalgo" },
      { id: 438, name: "Koko/Besse" },
      { id: 439, name: "Maiyama" },
      { id: 440, name: "Ngaski" },
      { id: 441, name: "Sakaba" },
      { id: 442, name: "Shanga" },
      { id: 443, name: "Suru" },
      { id: 444, name: "Wasagu/Danko" },
      { id: 445, name: "Yauri" },
      { id: 446, name: "Zuru" },
    ],
    code: "000068",
  },
  {
    id: 23,
    name: "Kogi",
    lga: [
      { id: 447, name: "Ajaokuta" },
      { id: 448, name: "Ankpa" },
      { id: 449, name: "Bassa" },
      { id: 450, name: "Dekina" },
      { id: 451, name: "Ibaji" },
      { id: 452, name: "Idah" },
      { id: 453, name: "Igalamela Odolu" },
      { id: 454, name: "Ijumu" },
      { id: 455, name: "Kabba/Bunu" },
      { id: 456, name: "Kogi" },
      { id: 457, name: "Lokoja" },
      { id: 458, name: "Mopa Muro" },
      { id: 459, name: "Ofu" },
      { id: 460, name: "Ogori/Magongo" },
      { id: 461, name: "Okehi" },
      { id: 462, name: "Okene" },
      { id: 463, name: "Olamaboro" },
      { id: 464, name: "Omala" },
      { id: 465, name: "Yagba East" },
      { id: 466, name: "Yagba West" },
    ],
    code: "000058",
  },
  {
    id: 24,
    name: "Kwara",
    lga: [
      { id: 467, name: "Baruten" },
      { id: 468, name: "Edu" },
      { id: 469, name: "Ekiti" },
      { id: 470, name: "Ifelodun" },
      { id: 471, name: "Ilorin East" },
      { id: 472, name: "Ilorin South" },
      { id: 473, name: "Ilorin West" },
      { id: 474, name: "Irepodun" },
      { id: 475, name: "Isin" },
      { id: 476, name: "Kaiama" },
      { id: 477, name: "Moro" },
      { id: 478, name: "Offa" },
      { id: 479, name: "Oke Ero" },
      { id: 480, name: "Oyun" },
      { id: 481, name: "Pategi" },
    ],
    code: "000031",
  },
  {
    id: 25,
    name: "Lagos",
    lga: [
      { id: 482, name: "Ajeromi-Ifelodun" },
      { id: 483, name: "Alimosho" },
      { id: 484, name: "Amuwo-Odofin" },
      { id: 485, name: "Apapa" },
      { id: 486, name: "Badagry" },
      { id: 487, name: "Epe" },
      { id: 488, name: "Eti Osa" },
      { id: 489, name: "Ibeju-Lekki" },
      { id: 490, name: "Ifako-Ijaiye" },
      { id: 491, name: "Ikeja" },
      { id: 492, name: "Ikorodu" },
      { id: 493, name: "Kosofe" },
      { id: 494, name: "Lagos Island" },
      { id: 495, name: "Lagos Mainland" },
      { id: 496, name: "Mushin" },
      { id: 497, name: "Ojo" },
      { id: 498, name: "Oshodi-Isolo" },
      { id: 499, name: "Shomolu" },
      { id: 500, name: "Surulere" },
    ],
    code: "000026",
  },
  {
    id: 26,
    name: "Nasarawa",
    lga: [
      { id: 501, name: "Awe" },
      { id: 502, name: "Doma" },
      { id: 503, name: "Karu" },
      { id: 504, name: "Keana" },
      { id: 505, name: "Keffi" },
      { id: 506, name: "Kokona" },
      { id: 507, name: "Lafia" },
      { id: 508, name: "Nasarawa" },
      { id: 509, name: "Nasarawa Egon" },
      { id: 510, name: "Obi" },
      { id: 511, name: "Toto" },
      { id: 512, name: "Wamba" },
    ],
    code: "000047",
  },
  {
    id: 27,
    name: "Niger",
    lga: [
      { id: 513, name: "Agwara" },
      { id: 514, name: "Bida" },
      { id: 515, name: "Borgu" },
      { id: 516, name: "Bosso" },
      { id: 517, name: "Chanchaga" },
      { id: 518, name: "Edati" },
      { id: 519, name: "Gbako" },
      { id: 520, name: "Gurara" },
      { id: 521, name: "Katcha" },
      { id: 522, name: "Kontagora" },
      { id: 523, name: "Lapai" },
      { id: 524, name: "Lavun" },
      { id: 525, name: "Magama" },
      { id: 526, name: "Mariga" },
      { id: 527, name: "Mashegu" },
      { id: 528, name: "Mokwa" },
      { id: 529, name: "Moya" },
      { id: 530, name: "Paikoro" },
      { id: 531, name: "Rafi" },
      { id: 532, name: "Rijau" },
      { id: 533, name: "Shiroro" },
      { id: 534, name: "Suleja" },
      { id: 535, name: "Tafa" },
      { id: 536, name: "Wushishi" },
    ],
    code: "000066",
  },
  {
    id: 28,
    name: "Ogun",
    lga: [
      { id: 537, name: "Abeokuta South" },
      { id: 538, name: "Ado-Odo/Ota" },
      { id: 539, name: "Egbado North" },
      { id: 540, name: "Egbado South" },
      { id: 541, name: "Ewekoro" },
      { id: 542, name: "Ifo" },
      { id: 543, name: "Ijebu East" },
      { id: 544, name: "Ijebu North" },
      { id: 545, name: "Ijebu North East" },
      { id: 546, name: "Ijebu Ode" },
      { id: 547, name: "Ikenne" },
      { id: 548, name: "Imeko Afon" },
      { id: 549, name: "Ipokia" },
      { id: 550, name: "Obafemi Owode" },
      { id: 551, name: "Odeda" },
      { id: 552, name: "Odogbolu" },
      { id: 553, name: "Ogun Waterside" },
      { id: 554, name: "Remo North" },
      { id: 555, name: "Shagamu" },
    ],
    code: "000039",
  },
  {
    id: 29,
    name: "Ondo",
    lga: [
      { id: 556, name: "Akoko North-West" },
      { id: 557, name: "Akoko South-West" },
      { id: 558, name: "Akoko South-East" },
      { id: 559, name: "Akure North" },
      { id: 560, name: "Akure South" },
      { id: 561, name: "Ese Odo" },
      { id: 562, name: "Idanre" },
      { id: 563, name: "Ifedore" },
      { id: 564, name: "Ilaje" },
      { id: 565, name: "Ile Oluji/Okeigbo" },
      { id: 566, name: "Irele" },
      { id: 567, name: "Odigbo" },
      { id: 568, name: "Okitipupa" },
      { id: 569, name: "Ondo East" },
      { id: 570, name: "Ondo West" },
      { id: 571, name: "Ose" },
      { id: 572, name: "Owo" },
    ],
    code: "000034",
  },
  {
    id: 30,
    name: "Osun",
    lga: [
      { id: 573, name: "Atakunmosa West" },
      { id: 574, name: "Aiyedaade" },
      { id: 575, name: "Aiyedire" },
      { id: 576, name: "Boluwaduro" },
      { id: 577, name: "Boripe" },
      { id: 578, name: "Ede North" },
      { id: 579, name: "Ede South" },
      { id: 580, name: "Ife Central" },
      { id: 581, name: "Ife East" },
      { id: 582, name: "Ife North" },
      { id: 583, name: "Ife South" },
      { id: 584, name: "Egbedore" },
      { id: 585, name: "Ejigbo" },
      { id: 586, name: "Ifedayo" },
      { id: 587, name: "Ifelodun" },
      { id: 588, name: "Ila" },
      { id: 589, name: "Ilesa East" },
      { id: 590, name: "Ilesa West" },
      { id: 591, name: "Irepodun" },
      { id: 592, name: "Irewole" },
      { id: 593, name: "Isokan" },
      { id: 594, name: "Iwo" },
      { id: 595, name: "Obokun" },
      { id: 596, name: "Odo Otin" },
      { id: 597, name: "Ola Oluwa" },
      { id: 598, name: "Olorunda" },
      { id: 599, name: "Oriade" },
      { id: 600, name: "Orolu" },
      { id: 601, name: "Osogbo" },
    ],
    code: "000035",
  },
  {
    id: 31,
    name: "Oyo",
    lga: [
      { id: 602, name: "Akinyele" },
      { id: 603, name: "Atiba" },
      { id: 604, name: "Atisbo" },
      { id: 605, name: "Egbeda" },
      { id: 606, name: "Ibadan North" },
      { id: 607, name: "Ibadan North-East" },
      { id: 608, name: "Ibadan North-West" },
      { id: 609, name: "Ibadan South-East" },
      { id: 610, name: "Ibadan South-West" },
      { id: 611, name: "Ibarapa Central" },
      { id: 612, name: "Ibarapa East" },
      { id: 613, name: "Ibarapa North" },
      { id: 614, name: "Ido" },
      { id: 615, name: "Irepo" },
      { id: 616, name: "Iseyin" },
      { id: 617, name: "Itesiwaju" },
      { id: 618, name: "Iwajowa" },
      { id: 619, name: "Kajola" },
      { id: 620, name: "Lagelu" },
      { id: 621, name: "Ogbomosho North" },
      { id: 622, name: "Ogbomosho South" },
      { id: 623, name: "Ogo Oluwa" },
      { id: 624, name: "Olorunsogo" },
      { id: 625, name: "Oluyole" },
      { id: 626, name: "Ona Ara" },
      { id: 627, name: "Orelope" },
      { id: 628, name: "Ori Ire" },
      { id: 629, name: "Oyo" },
      { id: 630, name: "Oyo East" },
      { id: 631, name: "Saki East" },
      { id: 632, name: "Saki West" },
      { id: 633, name: "Surulere" },
    ],
    code: "000020",
  },
  {
    id: 32,
    name: "Plateau",
    lga: [
      { id: 634, name: "Barkin Ladi" },
      { id: 635, name: "Bassa" },
      { id: 636, name: "Jos East" },
      { id: 637, name: "Jos North" },
      { id: 638, name: "Jos South" },
      { id: 639, name: "Kanam" },
      { id: 640, name: "Kanke" },
      { id: 641, name: "Langtang South" },
      { id: 642, name: "Langtang North" },
      { id: 643, name: "Mangu" },
      { id: 644, name: "Mikang" },
      { id: 645, name: "Pankshin" },
      { id: 646, name: "Qua'an Pan" },
      { id: 647, name: "Riyom" },
      { id: 648, name: "Shendam" },
      { id: 649, name: "Wase" },
    ],
    code: "000073",
  },
  {
    id: 33,
    name: "Rivers",
    lga: [
      { id: 650, name: "Ahoada East" },
      { id: 651, name: "Ahoada West" },
      { id: 652, name: "Akuku-Toru" },
      { id: 653, name: "Andoni" },
      { id: 654, name: "Asari-Toru" },
      { id: 655, name: "Bonny" },
      { id: 656, name: "Degema" },
      { id: 657, name: "Eleme" },
      { id: 658, name: "Emuoha" },
      { id: 659, name: "Etche" },
      { id: 660, name: "Gokana" },
      { id: 661, name: "Ikwerre" },
      { id: 662, name: "Khana" },
      { id: 663, name: "Obio/Akpor" },
      { id: 664, name: "Ogba/Egbema/Ndoni" },
      { id: 665, name: "Ogu/Bolo" },
      { id: 666, name: "Okrika" },
      { id: 667, name: "Omuma" },
      { id: 668, name: "Opobo/Nkoro" },
      { id: 669, name: "Oyigbo" },
      { id: 670, name: "Port Harcourt" },
      { id: 671, name: "Tai" },
    ],
    code: "000084",
  },
  {
    id: 34,
    name: "Sokoto",
    lga: [
      { id: 672, name: "Bodinga" },
      { id: 673, name: "Dange Shuni" },
      { id: 674, name: "Gada" },
      { id: 675, name: "Goronyo" },
      { id: 676, name: "Gudu" },
      { id: 677, name: "Gwadabawa" },
      { id: 678, name: "Illela" },
      { id: 679, name: "Isa" },
      { id: 680, name: "Kebbe" },
      { id: 681, name: "Kware" },
      { id: 682, name: "Rabah" },
      { id: 683, name: "Sabon Birni" },
      { id: 684, name: "Shagari" },
      { id: 685, name: "Silame" },
      { id: 686, name: "Sokoto North" },
      { id: 687, name: "Sokoto South" },
      { id: 688, name: "Tambuwal" },
      { id: 689, name: "Tangaza" },
      { id: 690, name: "Tureta" },
      { id: 691, name: "Wamako" },
      { id: 692, name: "Wurno" },
      { id: 693, name: "Yabo" },
    ],
    code: "000060",
  },
  {
    id: 35,
    name: "Taraba",
    lga: [
      { id: 694, name: "Bali" },
      { id: 695, name: "Donga" },
      { id: 696, name: "Gashaka" },
      { id: 697, name: "Gassol" },
      { id: 698, name: "Ibi" },
      { id: 699, name: "Jalingo" },
      { id: 700, name: "Karim Lamido" },
      { id: 701, name: "Kumi" },
      { id: 702, name: "Lau" },
      { id: 703, name: "Sardauna" },
      { id: 704, name: "Takum" },
      { id: 705, name: "Ussa" },
      { id: 706, name: "Wukari" },
      { id: 707, name: "Yorro" },
      { id: 708, name: "Zing" },
    ],
    code: "000079",
  },
  {
    id: 36,
    name: "Yobe",
    lga: [
      { id: 709, name: "Bursari" },
      { id: 710, name: "Damaturu" },
      { id: 711, name: "Fika" },
      { id: 712, name: "Fune" },
      { id: 713, name: "Geidam" },
      { id: 714, name: "Gujba" },
      { id: 715, name: "Gulani" },
      { id: 716, name: "Jakusko" },
      { id: 717, name: "Karasuwa" },
      { id: 718, name: "Machina" },
      { id: 719, name: "Nangere" },
      { id: 720, name: "Nguru" },
      { id: 721, name: "Potiskum" },
      { id: 722, name: "Tarmuwa" },
      { id: 723, name: "Yunusari" },
      { id: 724, name: "Yusufari" },
    ],
    code: "000032",
  },
  {
    id: 37,
    name: "Zamfara",
    lga: [
      { id: 725, name: "Bakura" },
      { id: 726, name: "Birnin Magaji/Kiyaw" },
      { id: 727, name: "Bukkuyum" },
      { id: 728, name: "Bungudu" },
      { id: 729, name: "Gummi" },
      { id: 730, name: "Gusau" },
      { id: 731, name: "Kaura Namoda" },
      { id: 732, name: "Maradun" },
      { id: 733, name: "Maru" },
      { id: 734, name: "Shinkafi" },
      { id: 735, name: "Talata Mafara" },
      { id: 736, name: "Chafe" },
      { id: 737, name: "Zurmi" },
    ],
    code: "000074",
  },
];
